// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: sixprotocol/nftmngr/attribute_of_schema.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SchemaAttribute } from "./schema_attribute";

export const protobufPackage = "sixprotocol.nftmngr";

export interface AttributeOfSchema {
  nftSchemaCode: string;
  schemaAttributes: SchemaAttribute[];
}

function createBaseAttributeOfSchema(): AttributeOfSchema {
  return { nftSchemaCode: "", schemaAttributes: [] };
}

export const AttributeOfSchema: MessageFns<AttributeOfSchema> = {
  encode(message: AttributeOfSchema, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nftSchemaCode !== "") {
      writer.uint32(10).string(message.nftSchemaCode);
    }
    for (const v of message.schemaAttributes) {
      SchemaAttribute.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AttributeOfSchema {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttributeOfSchema();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nftSchemaCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.schemaAttributes.push(SchemaAttribute.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AttributeOfSchema {
    return {
      nftSchemaCode: isSet(object.nftSchemaCode) ? globalThis.String(object.nftSchemaCode) : "",
      schemaAttributes: globalThis.Array.isArray(object?.schemaAttributes)
        ? object.schemaAttributes.map((e: any) => SchemaAttribute.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AttributeOfSchema): unknown {
    const obj: any = {};
    if (message.nftSchemaCode !== "") {
      obj.nftSchemaCode = message.nftSchemaCode;
    }
    if (message.schemaAttributes?.length) {
      obj.schemaAttributes = message.schemaAttributes.map((e) => SchemaAttribute.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AttributeOfSchema>, I>>(base?: I): AttributeOfSchema {
    return AttributeOfSchema.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AttributeOfSchema>, I>>(object: I): AttributeOfSchema {
    const message = createBaseAttributeOfSchema();
    message.nftSchemaCode = object.nftSchemaCode ?? "";
    message.schemaAttributes = object.schemaAttributes?.map((e) => SchemaAttribute.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
