// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: sixprotocol/nftoracle/oracle_config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sixprotocol.nftoracle";

export interface OracleConfig {
  minimumConfirmation: number;
}

function createBaseOracleConfig(): OracleConfig {
  return { minimumConfirmation: 0 };
}

export const OracleConfig: MessageFns<OracleConfig> = {
  encode(message: OracleConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.minimumConfirmation !== 0) {
      writer.uint32(8).int32(message.minimumConfirmation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OracleConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOracleConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.minimumConfirmation = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OracleConfig {
    return {
      minimumConfirmation: isSet(object.minimumConfirmation) ? globalThis.Number(object.minimumConfirmation) : 0,
    };
  },

  toJSON(message: OracleConfig): unknown {
    const obj: any = {};
    if (message.minimumConfirmation !== 0) {
      obj.minimumConfirmation = Math.round(message.minimumConfirmation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OracleConfig>, I>>(base?: I): OracleConfig {
    return OracleConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OracleConfig>, I>>(object: I): OracleConfig {
    const message = createBaseOracleConfig();
    message.minimumConfirmation = object.minimumConfirmation ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
